name: build test

on:
  push:
    branches:
      - master
      - try-action

jobs:
  build:
    name: build test

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        go: [1.12, 1.13]

    steps:
      - name: checkout codes
        uses: actions/checkout@v1

      - name: install go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}

      - name: install go dependencies
        run: go mod download

      - name: test
        run: go test -v ./...
